# Generated by Django 2.1.2 on 2018-12-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gbom',
            options={'verbose_name': 'GBOM', 'verbose_name_plural': 'GBOM'},
        ),
        migrations.RenameField(
            model_name='gbom',
            old_name='gbom',
            new_name='GBOM',
        ),
        migrations.AddField(
            model_name='maintenance_history',
            name='check_in_week',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
