# Generated by Django 2.1.2 on 2018-12-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0004_auto_20181206_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMachineUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lot', models.TextField()),
                ('Period', models.TextField()),
                ('Machine', models.TextField()),
            ],
            options={
                'db_table': 'HistoryMachineUsage',
            },
        ),
        migrations.CreateModel(
            name='HistoryMachineYieldRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Machine', models.TextField()),
                ('Period', models.TextField()),
                ('YieldRate', models.TextField()),
                ('ProcessedPieces', models.TextField()),
                ('AnalyseType', models.TextField(default='Cell')),
            ],
            options={
                'db_table': 'HistoryMachineYieldRate',
            },
        ),
        migrations.CreateModel(
            name='MachineUsedByLotInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaterialNumber', models.TextField()),
                ('GBOM', models.TextField()),
                ('Lot', models.CharField(db_index=True, max_length=255)),
                ('FinishTime', models.TextField()),
                ('TypeSettingNumber', models.TextField()),
                ('Machine', models.CharField(max_length=255)),
                ('CheckInTime', models.TextField()),
                ('CheckOutTime', models.TextField()),
                ('StationNumber', models.TextField()),
                ('GoodPieces', models.TextField()),
                ('BadPieces', models.TextField()),
                ('FirstStation', models.TextField()),
                ('CurrentTotalPieces', models.TextField()),
                ('Period', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'MachineUsedByLotInformation',
            },
        ),
        migrations.RenameField(
            model_name='gbom',
            old_name='GBOM',
            new_name='gbom',
        ),
        migrations.AlterIndexTogether(
            name='machineusedbylotinformation',
            index_together={('Period', 'Machine')},
        ),
    ]
