# Generated by Django 2.1.2 on 2018-12-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0005_auto_20181211_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineYieldRateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.TextField()),
                ('period', models.TextField()),
                ('yield_rate', models.TextField()),
                ('processed_pieces', models.TextField()),
                ('analyze_type', models.TextField(default='Cell')),
            ],
            options={
                'verbose_name': 'Machine Yield Rate History',
                'verbose_name_plural': 'Machine Yield Rate Histories',
            },
        ),
        migrations.DeleteModel(
            name='HistoryMachineYieldRate',
        ),
    ]
