# Generated by Django 2.1.2 on 2018-12-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0006_auto_20181212_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineyieldratehistory',
            options={'ordering': ['yield_rate'], 'verbose_name': 'Machine Yield Rate History', 'verbose_name_plural': 'Machine Yield Rate Histories'},
        ),
    ]
