# Generated by Django 2.1.2 on 2018-12-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0007_auto_20181212_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MachineYieldRateHistory',
            new_name='Machine_Yield_Rate_History',
        ),
    ]
