# Generated by Django 2.1.2 on 2018-12-12 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0008_auto_20181212_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine_yield_rate_history',
            old_name='period',
            new_name='end_period',
        ),
        migrations.AddField(
            model_name='machine_yield_rate_history',
            name='start_period',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
