# Generated by Django 2.1.2 on 2018-12-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0010_auto_20181212_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_yield_rate_history',
            name='yield_rate',
            field=models.FloatField(),
        ),
    ]
